image: ruby:2.3

before_script:
  - ruby -v
  - which ruby

test:
  before_script:
    - gem install bundler --no-ri --no-rdoc
    - bundle install --retry=3
  script:
    - rake test

gem/build:
  dependencies:
    - test
  script:
    - rake gem:build
  artifacts:
    paths:
      - pkg/
