image: ruby:2.3

cache:
  key: vendor
  paths:
    - vendor

variables:
  GEM_HOME: vendor

stages:
  - prepare
  - test
  - gem:build
  - gem:release

prepare:
  stage: prepare
  script:
    - gem install bundler --no-ri --no-rdoc
    - bundle install --retry=3 --path vendor
    - ls vendor

info:
  stage: test
  script:
    - uname -a
    - whoami
    - pwd
    - ruby -v
    - which ruby
    - gem env
    - gem list
    - ls -al

test:
  stage: test
  script:
    - ls vendor
    - rake test

gem:build:
  stage: gem:build
  script:
    - rake gem:build
  artifacts:
    paths:
      - pkg/

gem:release:
  when: manual
  stage: gem:release
  script:
    - rake gem:release
