image: ruby:2.3

info:
  script:
    - uname -a
    - whoami
    - pwd
    - ruby -v
    - which ruby
    - ls -al

stages:
  - prepare
  - test
  - gem:build

prepare:
  stage: prepare
  script:
    - gem install bundler --no-ri --no-rdoc
    - bundle install --retry=3

test:
  stage: test
  script:
    - rake test

gem:build:
  stage: gem:build
  script:
    - rake gem:build
  artifacts:
    paths:
      - pkg/

gem:release:
  when: manual
  stage: gem:release
  script:
    - rake gem:release
