image: ruby:2.3

before_script:
  - pwd
  - ruby -v
  - which ruby

stages:
  - test
  - gem:build

test:
  stage: test
  before_script:
    - gem install bundler --no-ri --no-rdoc
    - bundle install --retry=3
  script:
    - rake test

gem:build:
  stage: gem:build
  script:
    - rake gem:build
  artifacts:
    paths:
      - pkg/
